config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bindles, only: [:index, :show, :update, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bindle.rb
class Bindle < ApplicationRecord
  validates :name, presence: true
  validates :country, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :picture, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bindles_controller.rb
class BindlesController < ApplicationController


  def index
    @bindles = Bindle.all
  end

  def show
    @bindle = Bindle.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bindles_helper.rb
module BindlesHelper
end

app/views/bindles/index.html.erb
<div class="text-center">
  <%= link_to root_path do %>
    <%= image_tag "FF.png", class:"logo-pages"%>
  <% end %>
</div>

<div class="container">
  <div class="row">

    <% @bindles.each do |bindle| %>
      <div class="col-xs-12 col-md-4">
        <div class="index-card text-center">
          <%= link_to bindle_path(bindle) do %>
            <div class="card">
              <%= image_tag bindle.picture, class: "card"%>
            </div>
          <% end %>
          <div class="card-description">
              <h2><%= bindle.name %></h2>
              <p><%= bindle.country %></p>
          </div>
        </div> <!-- end of index-card -->
      </div> <!-- end of col -->
    <% end %>
    </div>
  </div> <!-- end of row -->
</div> <!-- end of container -->

app/views/bindles/show.html.erb
<div class="text-center">
  <%= link_to root_path do %>
    <%= image_tag "FF.png", class:"logo-pages"%>
  <% end %>
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="card-show">
        <%= image_tag @bindle.picture, class: "card-show"%>
      </div>
    </div> <!-- fin col-md-6 -->

    <div class="col-xs-12 col-md-6">
      <div class="show-description text-center">
        <h3><%= @bindle.name %></h3>
        <h4>Baluchon <%= @bindle.country %></h4>
        <p>
          <i class="fa fa-quote-left" aria-hidden="true"></i>
          <%= @bindle.description %>
          <i class="fa fa-quote-right" aria-hidden="true"></i>
        </p>
        <p><%= @bindle.price %> €</p>
      </div>
    </div> <!-- fin col-md-6 -->

  </div> <!-- fin row -->
</div> <!-- fin container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Food & Folks</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Bad+Script|Raleway|Waiting+for+the+Sunrise" rel="stylesheet">
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="page-home">

    <p class="warning text-center">Site vitrine réalisé avec Rails pour présenter le concept de Food & Folks sur base de l'ancienne plateforme e-commerce sans la partie marchande</p>

    <div class="navbar-ff">
      <!-- Logo -->
      <%= link_to root_path do %>
        <%= image_tag "FF.png", class:"logo"%>
      <% end %>

      <!-- Right Navigation -->
      <div class="navbar-ff-right hidden-xs hidden-sm text-center">

        <!-- Text link -->
        <a href="#concept" class="navbar-ff-item navbar-ff-link">CONCEPT</a>

        <a href="#baluchon" class="navbar-ff-item navbar-ff-link">BALUCHONS DU MONDE</a>

        <!-- <a href="" class="navbar-ff-item navbar-ff-link">MAGAZINE</a> -->

        <a href="#contact" class="navbar-ff-item navbar-ff-link">HISTOIRE & CONTACT</a>

        <!-- Dropdown appearing on mobile only -->
        <div class="navbar-ff-item hidden-md hidden-lg">
          <div class="dropdown">
            <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
            <ul class="dropdown-menu dropdown-menu-right navbar-ff-dropdown-menu">
              <li><a href="#">Some mobile link</a></li>
              <li><a href="#">Other one</a></li>
              <li><a href="#">Other one</a></li>
            </ul>
          </div> <!-- End of dropdown -->
        </div> <!-- End of navar-ff-item -->
      </div> <!-- End of navar-ff-right -->
    </div> <!-- End of navar-ff -->

    <!-- End of Navbar -->



    <div class="banner-content">

      <!-- Beginning of Slider -->
      <ul class="slides">
          <input type="radio" name="radio-btn" id="img-1" checked />
          <li class="slide-container">
          <div class="slide">
            <%= image_tag "slider/mali.jpg"%>
              </div>
          <div class="nav">
            <label for="img-6" class="prev">&#x2039;</label>
            <label for="img-2" class="next">&#x203a;</label>
          </div>
          </li>

          <input type="radio" name="radio-btn" id="img-2" />
          <li class="slide-container">
              <div class="slide">
                <%= image_tag "slider/concept.jpg"%>
              </div>
          <div class="nav">
            <label for="img-1" class="prev">&#x2039;</label>
            <label for="img-3" class="next">&#x203a;</label>
          </div>
          </li>

          <input type="radio" name="radio-btn" id="img-3" />
          <li class="slide-container">
              <div class="slide">
                <%= image_tag "slider/fdm.jpg"%>
              </div>
          <div class="nav">
            <label for="img-2" class="prev">&#x2039;</label>
            <label for="img-4" class="next">&#x203a;</label>
          </div>
          </li>

          <input type="radio" name="radio-btn" id="img-4" />
          <li class="slide-container">
              <div class="slide">
                <%= image_tag "slider/bresil.jpg"%>
              </div>
          <div class="nav">
            <label for="img-3" class="prev">&#x2039;</label>
            <label for="img-5" class="next">&#x203a;</label>
          </div>
          </li>

          <input type="radio" name="radio-btn" id="img-5" />
          <li class="slide-container">
              <div class="slide">
                <%= image_tag "slider/presentation.jpg"%>
              </div>
          <div class="nav">
            <label for="img-4" class="prev">&#x2039;</label>
            <label for="img-6" class="next">&#x203a;</label>
          </div>
          </li>

          <input type="radio" name="radio-btn" id="img-6" />
          <li class="slide-container">
              <div class="slide">
                <%= image_tag "slider/algerie.jpg"%>
              </div>
          <div class="nav">
            <label for="img-5" class="prev">&#x2039;</label>
            <label for="img-1" class="next">&#x203a;</label>
          </div>
          </li>

          <li class="nav-dots">
            <label for="img-1" class="nav-dot" id="img-dot-1"></label>
            <label for="img-2" class="nav-dot" id="img-dot-2"></label>
            <label for="img-3" class="nav-dot" id="img-dot-3"></label>
            <label for="img-4" class="nav-dot" id="img-dot-4"></label>
            <label for="img-5" class="nav-dot" id="img-dot-5"></label>
            <label for="img-6" class="nav-dot" id="img-dot-6"></label>
          </li>
        </ul>

      <!-- End of Slider -->

<!--       <div class="text-center">
        <a href="#concept">
          <%#= image_tag "arrow.svg", class: "floating arrow-img", width: 80 %>
        </a>
      </div> -->

      </div> <!-- end of banner-content -->

      <div class="container">
        <div class="row">
          <div class="col-xs-12">

          <!-- Presentation of the concept  -->

            <div class="banner-concept" id="concept">

              <h1>Food & Folks</h1>
              <p class="presentation-text">
                Food & Folks permet de découvrir les spécialités traditionnelles du monde avec un coffret de produits d'épicerie fine du monde.
                Un baluchon regroupe plusieurs produits typiques à cuisiner, et un carnet de culture avec recettes et conseils de locaux, une playlist. Tout ce qu'il faut pour s'initier à une culture !
              </p>

              <div class="container">
                <div class="row">
                  <div class="col-xs-12 col-md-3">
                    <div class="text-center">
                      <%= image_tag "home/balu.jpg", class: "home-button"%>
                      <h4>Commandez un baluchon</h4>
                    </div>
                  </div>
                  <div class="col-xs-12 col-md-3">
                    <div class="text-center">
                      <%= image_tag "home/mag.jpg", class: "home-button"%>
                      <h4>Parcourez le magazine</h4>
                    </div>
                  </div>
                  <div class="col-xs-12 col-md-3">
                    <div class="text-center">
                      <%= image_tag "home/radio.jpg", class: "home-button"%>
                      <h4>Ecoutez les folks du monde</h4>
                      </div>
                  </div>
                  <div class="col-xs-12 col-md-3">
                    <div class="text-center">
                      <%= image_tag "home/unit.jpg", class: "home-button"%>
                      <h4>Laissez vous séduire par les produits</h4>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- End of banner-concept -->
          </div> <!-- End of col-xs-12 -->

          <div class="col-xs-12">

            <div class="banner-baluchon" id="baluchon">
              <h1>Les Baluchons</h1>

              <div class="container">
                <div class="row">
                  <div class="col-xs-12 col-sm-6">
                    <div class="text-center">
                      <%= image_tag "baluchon/italie.jpg", class: "card-balu"%>
                      <h4>Voyage en Italie</h4>
                    </div>
                  </div>
                  <div class="col-xs-12 col-sm-6">
                    <div class="text-center">
                      <%= image_tag "baluchon/mali.jpg", class: "card-balu"%>
                      <h4>De Dakar à Bamako</h4>
                    </div>
                  </div>
                </div> <!-- end of row -->
              </div> <!-- end of container -->

              <p class="text-center"><a href="/bindles" class="btn-medium">Voir plus!</a></p>

            </div> <!-- banner baluchon -->
          </div> <!-- End of col-xs-12 -->

          <div class="col-xs-12">
            <div class="banner-contact" id="contact">
              <h1> Qui suis-je ? </h1>
              <div class="container">
                <div class="row">
                  <div class="col-xs-12 col-md-2">
                    <div class="text-center">
                    <%= image_tag "table2.jpg", class: "card-contact" %>
                    </div>
                  </div>
                  <div class="col-xs-12 col-md-8">
                    <p class="contact-text text-center">
                      Mes meilleurs souvenirs de voyages sont ceux passés autour d'une table, <br>
                      les moments partagés à cuisiner ensemble, <br>
                      les découvertes de produits typiques parfois délicieux, surprenants, parfois étranges, <br>
                      les spécialités que l’on déniche pour ramener dans sa valise pour partager avec ses proches au retour ou pour prolonger l’expérience. <br>
                      <br>
                      Il n’y a pas de voyage sans cuisine, sans culture, sans rencontre. Quand je pense à mon voyage en Inde, c’est la cuisine indienne qui me vient à l’esprit. Elle a fait partie intégrante de mon voyage en me plongeant dans la culture. <br>
                      L’Inde ne serait pas l’Inde sans sa cuisine. <br>
                      <br>
                      Voilà, c’est de là qu’est né Food & Folks, retrouver ce qui fait la magie des voyages.
                      <br>
                      <br>
                      La société n'existe plus aujourd'hui, vous pouvez tout de même me contacter <br> <br> <a href="https://www.linkedin.com/in/coralie-collignon-22984319/" target="_blank" class="btn-medium">Par là</a>
                    </p>
                  </div>

                  <div class="col-xs-12 col-md-2">
                    <div class="text-center">
                    <%= image_tag "table.jpg", class: "card-contact" %>
                    </div>
                  </div>

            </div> <!-- End of row -->
          </div> <!-- End of container -->
        </div> <!-- End of banner -->
      </div> <!-- End of col-xs-12 -->

    </div> <!-- End of principal row -->
  </div><!-- End of principal container -->
</div> <!-- End of page-home -->